#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\project

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\build.ps1

